### ISSUE TITLE
Lacking proper authentication

### ISSUE THREAD

**Issue by basti** [VanjaJeftic/RPG-editor#2]
Note: this is the first issue. Please ignore it for now. You'll deal with these once the first/main PR is merged.

When accessing https://serene-caverns-52637.herokuapp.com/types or similar I'm getting an error message instead of being redirected to sign in page with a message that I should sign in to access that page. For example, https://serene-caverns-52637.herokuapp.com/users/edit does this properly.

**Comment by basti** [comment]
@VanjaJeftic the first sentence in this issue was: `Note: this is the first issue. Please ignore it for now. You'll deal with these once the first/main PR is merged.`

These issues were supposed to be separate pull requests. Where you'd learn about closing PR through commits and I could review each one separately. In the future, please read the instructions carefully and don't rush.

I'm going to review these issues within PR #1 and check them there. No need to do anything about it now.

**Comment by VanjaKljajic** [comment]
@basti my mistake I never worked with issues so I didn't know that I should treat them as separate user stories. So in the future, I should just create a pull request for each issue, and after you review it and close it, I should merge it to the master branch?

**Comment by basti** [comment]
@VanjaJeftic partially, yes. I'll explain how we are going to work with Issues once we have more of them. That's why I said in the first issue to ignore them for now.
